name: github_viewer
description: "Sample github explorer app"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  get_it: ^7.0.0
  rxdart: ^0.27.7
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
